/**
 * Client-side error hook for SvelteKit.
 *
 * The default `handleError` autogenerated in `.svelte-kit/generated/client/app.js`
 * only does `console.error(error)`, which causes uncaught hydration failures
 * (e.g. prop-type mismatches) to disappear silently — leaving the user staring
 * at a blank page with no breadcrumb.
 *
 * This hook:
 *   1. Prints the full stack so devtools / CDP captures it.
 *   2. Re-emits it on `window` as a `notias:error` event so a future error
 *      overlay component can subscribe without coupling to SvelteKit internals.
 *
 * Anything thrown by SvelteKit's load/runtime during hydration lands here.
 */
import type { HandleClientError } from "@sveltejs/kit";

export const handleError: HandleClientError = ({ error, event }) => {
  // SvelteKit hands us a serialized Error; revive to get the stack if present.
  const err =
    error instanceof Error
      ? error
      : new Error(typeof error === "string" ? error : "Unknown client error");

  // eslint-disable-next-line no-console
  console.error(
    `[notias] client error at ${event?.url?.pathname ?? "<unknown>"}:`,
    err,
  );

  if (typeof window !== "undefined") {
    try {
      window.dispatchEvent(
        new CustomEvent("notias:error", {
          detail: { message: err.message, stack: err.stack, pathname: event?.url?.pathname },
        }),
      );
    } catch {
      /* dispatchEvent can throw in test envs; never let it escape */
    }
  }
};

// Catch uncaught errors and unhandled promise rejections that bypass SvelteKit's
// `handleError` (e.g. a store crashing during onMount, a third-party library
// throwing). The `ErrorOverlay` component listens for the same event.
if (typeof window !== "undefined") {
  window.addEventListener("error", (e) => {
    window.dispatchEvent(
      new CustomEvent("notias:error", {
        detail: {
          message: e.message || "Uncaught error",
          stack: e.error?.stack,
          pathname: window.location.pathname,
        },
      }),
    );
  });
  window.addEventListener("unhandledrejection", (e) => {
    const reason = e.reason as { message?: string; stack?: string } | undefined;
    window.dispatchEvent(
      new CustomEvent("notias:error", {
        detail: {
          message: reason?.message ?? String(e.reason ?? "Unhandled promise rejection"),
          stack: reason?.stack,
          pathname: window.location.pathname,
        },
      }),
    );
  });
}